---
title: Gravity
email: hemangsk@gmail.com
description: The Liberal Jekyll Theme
baseurl: ''
url: http://yourdomain.com
twitter_username: hemang_kumar
github_username: hemangsk
paginate: 5
theme-dark: false
plugins:
- jekyll-paginate
- kramdown
markdown: kramdown
timezone: Etc/UTC
